### ISSUE TITLE
Get rid of the environment variable stuff

### ISSUE THREAD

**Issue by scottbarstow** [bandwidthcom/node-bandwidth-iris#2]
I've never, ever seen that done in a Node app.  Realize you were carrying forward convention from the others, but I don't want that in here.

**Comment by avbel** [comment]
These env variables areused in C# code too. I do node lib like C# lib.

**Comment by scottbarstow** [comment]
Yes I am aware.  I still don't want them

On Mon, Dec 1, 2014 at 1:31 AM, avbel notifications@github.com wrote:

> These env variables areused in C# code too. I do node lib like C# lib.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bandwidthcom/node-bandwidth-iris/issues/2#issuecomment-65025713
> .

## 

scottbarstow.com
@scottbarstow
