### ISSUE TITLE
Need to update package dependencies 

### ISSUE THREAD

**Issue by darioxtx** [bandwidthcom/node-bandwidth-iris#24]
=== npm audit security report ===                        

                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve                                                                                             
          Visit https://go.npm.me/audit-guide for additional guidance     
                                                                                
  Moderate        Regular Expression Denial of Service                          
  Package         mime                                                          
  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3                                  
  Dependency of   bandwidth-iris                                                
  Path            bandwidth-iris > superagent > form-data > mime          
  More info       https://nodesecurity.io/advisories/535                        
                                                                                
  Moderate        Regular Expression Denial of Service                          
  Package         mime                                                          
  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3                                  
  Dependency of   bandwidth-iris                                                
  Path            bandwidth-iris > superagent > mime                            
  More info       https://nodesecurity.io/advisories/535                        
                                                                                
  Low             Large gzip Denial of Service                                  
  Package         superagent                                                    
  Patched in      >=3.7.0                                                       
  Dependency of   bandwidth-iris                                                
  Path            bandwidth-iris > superagent                               
  More info       https://nodesecurity.io/advisories/479

**Comment by jmulford-bw** [comment]
Hey @darioxtx,

Thanks for submitting this issue. I fixed this a few weeks ago, forgot to post here! We did decide to do a major update for this SDK, so version 1.0.0 is now the stable one. Thanks again!

**Comment by darioxtx** [comment]
Thank you! New version is working fine.
