### ISSUE TITLE
disconnect returns  code: 5001,   message: 'Invalid input telephone number list',

### ISSUE THREAD

**Issue by johnwnowlin** [bandwidthcom/node-bandwidth-iris#3]
Trying to use iris.Disconnect.create recieved code: 5001,   message: 'Invalid input telephone number list', return. Followed logic into lib\disconnect.js and made the following change to var data =

``` js
var data = {
    disconnectTelephoneNumberOrder:{
      name: orderName,
      _nameXmlElement: "name",
      disconnectTelephoneNumberOrderType: {
        telephoneNumberList:
          numbers.map(function(number) {
            return {telephoneNumber: number};
          })
      }
    }
  };
```

No longer receive 'invalid input telephone number list', but only the last number in the list is actually deleted, based on getting the disconnect order and reviewing the TNS list.

**Comment by johnwnowlin** [comment]
Appears to be a limitation of xml2js which is converting the json object telephoneNumberList array into a  series of XML elements.

``` xml
<disconnectTelephoneNumberOrder>
  <name>Name</name>
  <_nameXmlElement>name</_nameXmlElement>
  <disconnectTelephoneNumberOrderType>
    <telephoneNumberList>
      <telephoneNumber>xxx</telephoneNumber>
    </telephoneNumberList>
    <telephoneNumberList>
      <telephoneNumber>xxx</telephoneNumber>
    </telephoneNumberList>
```

**Comment by dtolb** [comment]
Hey! Thanks for looking into this. I'll get back to you ASAP
