### ISSUE TITLE
TnReservation.create: JAXBException occurred

### ISSUE THREAD

**Issue by IgorBerezin** [bandwidthcom/node-bandwidth-iris#7]
JAXBException occurred : unexpected element (uri:"", local:"TnReservation"). Expected elements are <{}Reservation>

> var request = client.createPostRequest(client.concatAccountPath(TN_RESERVATION_PATH), {TnReservation: item});

```
iris.TnReservation.create(client, {"reservedTn": number}, function(err, reservation) {
  if (err) {
    return done(err);
  }
  if (!reservation || !reservation.reservationId) {
    return done('Phone number is not reserver!');
  }
}

```

**Comment by dtolb** [comment]
This is the example in the Dashboard API docs:

```
<Reservation>
    <ReservedTn>4354770625</ReservedTn>
</Reservation>
```

And this is what Node SDK is sending:

```
<TnReservation>
  <ReservedTn>5202315011</ReservedTn>
</TnReservation>
```

This is how I am making the request:

``` javascript
iris.TnReservation.create(
    {reservedTn: '5202315011'},
    next
);
```

[Docs Site](https://test.dashboard.bandwidth.com/apidocs/)

**Comment by avbel** [comment]
Fixed
