### ISSUE TITLE
boolean values not converted to xml correctly

### ISSUE THREAD

**Issue by chadxz** [bandwidthcom/node-bandwidth-iris#8]
I have the following request I was trying to make:

``` js
api.Order.create({
    siteId: '123456',
    partialAllowed: false,
    backOrderRequested: false,
    nPANXXSearchAndOrderType: {
        npaNxx: '256412',
        enableTNDetail: true,
        enableLCA: false,
        quantity: 2
    }
}, (err, results) => { });
```

but the xml that is being generated omits the properties that are set to false:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Order>
  <SiteId>10940</SiteId>
  <NPANXXSearchAndOrderType>
    <NpaNxx>256698</NpaNxx>
    <EnableTNDetail>true</EnableTNDetail>
    <Quantity>2</Quantity>
  </NPANXXSearchAndOrderType>
</Order>
```

I can work around this by making all my values strings in my request. 

I am filing this issue because it caused me problems and was counter-intuitive. It looks to be caused by [code in the client](https://github.com/bandwidthcom/node-bandwidth-iris/blob/fe11db75799e564b645c90415360372cdc4f475d/lib/client.js#L47) that is walking the object structure and doing a "!v" check to determine if the value exists. This is incorrect... there are many values in javascript that do not pass this check, such as `false` and `0`, that should be serialized to the xml.

**Comment by avbel** [comment]
Thanks for the issue. Please update to `0.0.9`

**Comment by chadxz** [comment]
thanks!
