### ISSUE TITLE
why is `explicitArray` disabled?

### ISSUE THREAD

**Issue by chadxz** [bandwidthcom/node-bandwidth-iris#9]
It's counterintuitive that a collection from the xml would sometimes be represented as a single value and sometimes an array in the js. And when the collection is completely empty, the js has a value of 0. Is there some reason it's disabled explicitly in client.js?

**Comment by chadxz** [comment]
So i looked into this a bit more. Disabling the explicitArray property causes the library to build javascript objects from the xml that feel more sane for the case of say, a tag like this: `<someTag>hi i am a value</someTag>` into javascript like `someTag: 'hi i am a value'`. With explicitArray turned on, it would be `someTag: ['hi i am a value']` which is a little annoying. However, for other scenarios, such as for a tag that is meant to hold a list of items, that's exactly what you want. So... idk what the right solution is, but I know the current behavior is funky and probably needs a little love to make it behave more like what one would expect.

**Comment by avbel** [comment]
`explicitArray` was `true` because most of xml elements have simple value. But I understand your wishes too. I added ability to change `xml2js` parser settings in code like 

``` js
client.xml2jsParserOptions.explicitArray = true;
client.xml2jsParserOptions.trim = true;
```

Now you can control `xml2js` parser in your code. to get estimated objects from XML. Please update to `0.0.10`.

**Comment by chadxz** [comment]
I don't really consider that a fix, it's just shifting the problem around, so instead of having to deal with one type of funkiness in my code I trade it for another. I would generally push this sort of complexity into the client library so that consumers don't have to think about it. Ideally the public api consumer shouldn't have to think about the xml encode/decode at all.

**Comment by chadxz** [comment]
not to mention, I don't know that the library would even work with the explicitArray set differently, as it probably assumes explicitArray to be false when doing some of its massaging of the data.

**Comment by avbel** [comment]
I set `explicitArray` to `true` by default because almost all elements from results have single values, not arrays. I think you also prefer to use code like `result.simpleValue` instead of `result.simpleValue[0]`. I agree my current solution is not so good for now. Need to find something more "strong-typed" for xml results in next major version of this lib to avoid possible issues with simple values and arrays (and other types).
